#!/bin/bash
for ARCH in arm32v7 arm64v8
do 
    sed 's/ARCH_PLACEHOLDER/'"$ARCH"'/g' ${DOCKERFILE_PATH}.arm > ${DOCKERFILE_PATH}.${ARCH}
    echo "########################################"
    echo "${DOCKERFILE_PATH}.${ARCH}: generated"
done
